spring.application.name=Lab04

# MySQL (fix lỗi: Public Key Retrieval is not allowed)
spring.datasource.url=jdbc:mysql://localhost:3306/demoproduct?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456Aa

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# (không bắt buộc) format SQL cho dễ đọc
spring.jpa.properties.hibernate.format_sql=true